package com.sap.xm.scheduler.batch.reader;

public enum BatchReaderQueryPool {

	CAMPAIGN_TIME_IMPRESSION_QUERY("SELECT ADRL.ADVERTISER_ID AS ADVERTISER_ID, ADRL.CAMPAIGN_ID AS CAMPAIGN_ID, TO_DATE(?) AS IMP_DATE, ? AS IMP_TIME, IFNULL(SUM(ADRL.VIEW),0) AS IMPRESSIONS, IFNULL(SUM(ADRL.CLICK),0) AS CLICKS, IFNULL(SUM(ADRL.CONVERSION),0) AS CONVERSIONS, CASE WHEN PRICING = 1 THEN 0 WHEN PRICING = 0 THEN IFNULL(SUM(ADRL.CHARGE),0) END AS IMP_SPEND, CASE WHEN PRICING = 1 THEN IFNULL(SUM(ADRL.CHARGE),0) WHEN PRICING = 0 THEN 0 END AS CLK_SPEND, ADRL.CURRENCY AS SPEND_CURRENCY FROM T_AD_REQUEST_LOG ADRL INNER JOIN T_CAMPAIGN CMPGN ON ADRL.CAMPAIGN_ID = CMPGN.ID WHERE VIEW_TIMESTAMP >= (?) AND VIEW_TIMESTAMP < (?) GROUP BY ADRL.ADVERTISER_ID, ADRL.CAMPAIGN_ID, CMPGN.TOTAL_BUDGET, ADRL.CURRENCY,ADRL.PRICING");

	private String query;

	BatchReaderQueryPool(String query){
		this.query = query;
	}
	
	public String getQuery(){
		return this.query;
	}
}
